// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebWayCMS.Data.DbContexts;

#nullable disable

namespace WebWayCMS.Data.Migrations.ContentZone
{
    [DbContext(typeof(ContentZoneContext))]
    [Migration("20260623010148_InitialContentZone")]
    partial class InitialContentZone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebWayCMS.Data.Models.ContentDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentMasterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PublicationEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.HasIndex("ParentMasterId");

                    b.HasIndex("Slug");

                    b.ToTable("Content", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebWayCMS.Data.Models.ContentZoneAssignmentDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentZoneId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentPageMasterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentZoneId")
                        .HasColumnType("uuid");

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ContentZoneId");

                    b.HasIndex("ParentPageMasterId", "SlotName")
                        .IsUnique()
                        .HasDatabaseName("IX_ContentZoneAssignments_PageSlot")
                        .HasFilter("\"ParentPageMasterId\" IS NOT NULL");

                    b.HasIndex("ParentZoneId", "SlotName")
                        .IsUnique()
                        .HasDatabaseName("IX_ContentZoneAssignments_ZoneSlot")
                        .HasFilter("\"ParentZoneId\" IS NOT NULL");

                    b.ToTable("ContentZoneAssignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContentZoneAssignments_OneParent", "(\"ParentPageMasterId\" IS NOT NULL AND \"ParentZoneId\" IS NULL) OR (\"ParentPageMasterId\" IS NULL AND \"ParentZoneId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("WebWayCMS.Data.Models.ContentZoneDTO", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("ContentId");

                    b.ToTable("ContentZones", (string)null);
                });

            modelBuilder.Entity("WebWayCMS.Data.Models.ContentZoneItemDTO", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ComponentPropertiesJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("ContentZoneId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("ViewName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("ContentId");

                    b.HasIndex("ContentZoneId", "Ordinal");

                    b.ToTable("ContentZoneItems", (string)null);
                });

            modelBuilder.Entity("WebWayCMS.Data.Models.ContentDTO", b =>
                {
                    b.OwnsMany("WebWayCMS.Data.Models.CustomField", "CustomFields", b1 =>
                        {
                            b1.Property<Guid>("ContentDTOId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("FieldName")
                                .IsRequired();

                            b1.Property<string>("TypeName")
                                .IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("ContentDTOId", "__synthesizedOrdinal");

                            b1.ToTable("Content");

                            b1.ToJson("CustomFields");

                            b1.WithOwner()
                                .HasForeignKey("ContentDTOId");
                        });

                    b.Navigation("CustomFields");
                });

            modelBuilder.Entity("WebWayCMS.Data.Models.ContentZoneAssignmentDTO", b =>
                {
                    b.HasOne("WebWayCMS.Data.Models.ContentZoneDTO", "ContentZone")
                        .WithMany()
                        .HasForeignKey("ContentZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebWayCMS.Data.Models.ContentZoneDTO", "ParentZone")
                        .WithMany()
                        .HasForeignKey("ParentZoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ContentZone");

                    b.Navigation("ParentZone");
                });

            modelBuilder.Entity("WebWayCMS.Data.Models.ContentZoneDTO", b =>
                {
                    b.HasOne("WebWayCMS.Data.Models.ContentDTO", "ContentMeta")
                        .WithOne()
                        .HasForeignKey("WebWayCMS.Data.Models.ContentZoneDTO", "ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentMeta");
                });

            modelBuilder.Entity("WebWayCMS.Data.Models.ContentZoneItemDTO", b =>
                {
                    b.HasOne("WebWayCMS.Data.Models.ContentDTO", "ContentMeta")
                        .WithOne()
                        .HasForeignKey("WebWayCMS.Data.Models.ContentZoneItemDTO", "ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebWayCMS.Data.Models.ContentZoneDTO", "ContentZone")
                        .WithMany("Items")
                        .HasForeignKey("ContentZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentMeta");

                    b.Navigation("ContentZone");
                });

            modelBuilder.Entity("WebWayCMS.Data.Models.ContentZoneDTO", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
