<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="WebWayCMS.Host.Tests" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.MicrosoftAccount" />
    <PackageReference Include="AspNet.Security.OAuth.GitHub" />
    <ProjectReference Include="..\WebWayCMS.Data\WebWayCMS.Data.csproj" />
    <ProjectReference Include="..\WebWayCMS.Identity\WebWayCMS.Identity.csproj" />
    <ProjectReference Include="..\WebWayCMS.Forms\WebWayCMS.Forms.csproj" />
    <ProjectReference Include="..\WebWayCMS.Routing\WebWayCMS.Routing.csproj" />
    <ProjectReference Include="..\WebWayCMS.ContentZones\WebWayCMS.ContentZones.csproj" />
    <ProjectReference Include="..\WebWayCMS.Core\WebWayCMS.Core.csproj" />
    <ProjectReference Include="..\WebWayCMS.Presentation\WebWayCMS.Presentation.csproj" />
    <ProjectReference Include="..\WebWayCMS.Admin\WebWayCMS.Admin.csproj" />
    <ProjectReference Include="..\WebWayCMS.Mcp\WebWayCMS.Mcp.csproj" />
  </ItemGroup>
</Project>
