// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebWayCMS.Data.DbContexts;

#nullable disable

namespace WebWayCMS.Data.Migrations.Page
{
    [DbContext(typeof(PageContext))]
    [Migration("20260618205817_InitialPage")]
    partial class InitialPage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebWayCMS.Data.Models.ContentDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentMasterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PublicationEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.HasIndex("ParentMasterId");

                    b.HasIndex("Slug");

                    b.ToTable("Content", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebWayCMS.Data.Models.PageDTO", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ControllerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ViewName")
                        .HasColumnType("text");

                    b.HasKey("ContentId");

                    b.HasIndex("Route");

                    b.ToTable("Pages", (string)null);
                });

            modelBuilder.Entity("WebWayCMS.Data.Models.ContentDTO", b =>
                {
                    b.OwnsMany("WebWayCMS.Data.Models.CustomField", "CustomFields", b1 =>
                        {
                            b1.Property<Guid>("ContentDTOId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("FieldName")
                                .IsRequired();

                            b1.Property<string>("TypeName")
                                .IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("ContentDTOId", "__synthesizedOrdinal");

                            b1.ToTable("Content");

                            b1.ToJson("CustomFields");

                            b1.WithOwner()
                                .HasForeignKey("ContentDTOId");
                        });

                    b.Navigation("CustomFields");
                });

            modelBuilder.Entity("WebWayCMS.Data.Models.PageDTO", b =>
                {
                    b.HasOne("WebWayCMS.Data.Models.ContentDTO", "ContentMeta")
                        .WithOne()
                        .HasForeignKey("WebWayCMS.Data.Models.PageDTO", "ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentMeta");
                });
#pragma warning restore 612, 618
        }
    }
}
