<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Include>[WebWayCMS.Core]*</Include>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\WebWayCMS.Core\WebWayCMS.Core.csproj" />
    <ProjectReference Include="..\..\WebWayCMS.Admin\WebWayCMS.Admin.csproj" />
  </ItemGroup>
</Project>
