<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" />
    <PackageReference Include="QRCoder" />
    <ProjectReference Include="..\WebWayCMS.Core\WebWayCMS.Core.csproj" />
    <ProjectReference Include="..\WebWayCMS.ContentZones\WebWayCMS.ContentZones.csproj" />
    <ProjectReference Include="..\WebWayCMS.Identity\WebWayCMS.Identity.csproj" />
  </ItemGroup>
</Project>
